### ISSUE TITLE
Compiled Python file exts missing from (also missing) .gitignore

### ISSUE THREAD

**Issue by laggycomputer** [Arthurdw/UwU#1]
I just wanted to put a warning out there that not having these file exts in (and not having a) `.gitignore` can be pretty dangerous for a project. Compiled files may get accidentally committed.

**Comment by Arthurdw** [comment]
This project is currently WIP.
Thanks for informing me tho!
But as I'm not really sure if this project will get continued I'm not sure if I will still put the time in this.

Greetings Arthur
